services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: recon
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo-data:
